export const Users = [
    {
        id:1,
        profilePicture:"person/1.jpeg",
        username:"Swapnil Sonawane",
    },
    {
        id:2,
        profilePicture:"person/2.jpeg",
        username:"Suyash Sonar",
    },
    {
        id:3,
        profilePicture:"person/3.jpeg",
        username:"vara thakre",
    },
    {
        id:4,
        profilePicture:"person/4.jpeg",
        username:"Akshat chauhdhari",
    },
    {
        id:5,
        profilePicture:"person/5.jpeg",
        username:"om patil",
    },
    {
        id:6,
        profilePicture:"person/6.jpeg",
        username:"uday londhe",
    },
    {
        id:7,
        profilePicture:"person/7.jpeg",
        username:"Atharva nigal",
    },
    {
        id:8,
        profilePicture:"person/8.jpeg",
        username:"Vaishanav ghenge",
    },
    {
        id:9,
        profilePicture:"person/9.jpeg",
        username:"Gaurav Dada",
    },
    {
        id:10,
        profilePicture:"person/10.jpeg",
        username:"Saurav Dada",
    }
];

export const Posts =[
    {
        id:1,
        desc:"Love for all hatered for none",
        photo:"post/1.jpeg",
        date:"5 mins ago",
        userId: 1,
        like:32,
        comment:9,
    },
    {
        id:2,
        photo:"post/2.jpeg",
        date:"15 mins ago",
        userId: 2,
        like:2,
        comment:1,
    },
    {
        id:3,
        photo:"post/3.jpeg",
        date:"25 mins ago",
        userId: 3,
        like:12,
        comment:34,
    },
    {
        id:4,
        photo:"post/4.jpeg",
        date:"30 mins ago",
        userId: 4,
        like:32,
        comment:9,
    },
    {
        id:5,
        photo:"post/5.jpeg",
        date:"35 mins ago",
        userId: 5,
        like:26,
        comment:8,
    },
    {
        id:6,
        desc:"ok",
        photo:"post/6.jpeg",
        date:"40 mins ago",
        userId: 6,
        like:37,
        comment:13,
    },
    {
        id:7,
        photo:"post/7.jpeg",
        date:"45 mins ago",
        userId: 7,
        like:14,
        comment:4,
    },
    {
        id:8,
        desc:"nice photo",
        photo:"post/8.jpeg",
        date:"47 mins ago",
        userId: 8,
        like:67,
        comment:23,
    },
    {
        id:9,
        photo:"post/9.jpeg",
        date:"50 mins ago",
        userId: 9,
        like:41,
        comment:19,
    },
    {
        id:10,
        desc:"nice wheather",
        photo:"post/10.jpeg",
        date:"55 mins ago",
        userId: 10,
        like:87,
        comment:46,
    },
]